name: Sync to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Repo
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TARGET_REPO_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Sync to GitHub Pages Repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git clone git@github.com:cytek04/cytek04.git target-repo
          rsync -av --delete --exclude '.git' ./ target-repo/
          cd target-repo
          git add .
          git commit -m "Sync from CallNote-Public-Site" || echo "No changes to commit"
          git push origin main

